baseURL = 'https://samoyed.blog/'
languageCode = 'en-us'
title = 'samoyed.blog'
theme = 'Stack'

copyright = "Jose A. Ramos Sanchez"
DefaultContentLanguage = "en"
hasCJKLanguage = false

[languages.en]
languageName = "English"
title = "samoyed.blog"
weight = 1

[languages.en.params.sidebar]
subtitle = "Blogs, essays, and write-ups on computer science, fiction, cooking and philosophy"

[languages.es]
languageName = "Spanish"
title = "samoyed.blog"
weight = 2

[languages.es.params.sidebar]
subtitle = "Blogs, ensayos, e informes de tecnología, ficción, cocina y filosofía"

# [services.disqus]
# shortname = "hugo-theme-stack"

[services.googleAnalytics]

[pagination]
pagerSize = 7

[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true
favicon = "/favicon.ico"

  [params.footer]
  since = 2_024

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 EST"

  [params.sidebar]
  # emoji = "🍥"

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"

  [params.article]
  math = false
  toc = false
  readingTime = true

    [params.article.license]
    enabled = true
    default = "Jose A. Ramos Sanchez. All rights reserved."

  [params.comments]
  enabled = true
  provider = "utterances"

    [params.comments.utterances]
    issueTerm = "pathname"
    repo = "jar2333/jar2333.github.io"
    label = "comments"

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.homepage]]
type = "categories"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

  [params.widgets.homepage.params]
  limit = 10

# [[params.widgets.page]]
# type = "toc"

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
main = [ ]

  [[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/jar2333"

    [menu.social.params]
    icon = "brand-github"

  [[menu.social]]
  identifier = "linkedin"
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/josearamossanchez/"

    [menu.social.params]
    icon = "brand-linkedin"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

# [markup.goldmark.extensions.passthrough]
# enable = true

#   [markup.goldmark.extensions.passthrough.delimiters]
#   block = [ [ "\\[", "\\]" ], [ "$$", "$$" ] ]
#   inline = [ [ "\\(", "\\)" ] ]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
